In [7]:
import pip


%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import sys
print(sys.executable)
print(sys.version)


/home/doroza10/anaconda3/envs/myenv2/bin/python
3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]


In [8]:
import numpy as np

# 1. Create

In [5]:
data = np.random.rand(2,3,4) # 2 arrays of 3 rows and 4 columns with random numbers
zeroes = np.zeros((2,2,2)) # 2 arrays of 2 rows and 2 columns with zeroes
full = np.full((2,2,2), 7) # 2 arrays of 2 rows and 2 columns with 7s
ones = np.ones((2,2,2)) # 2 arrays of 2 rows and 2 columns with ones

In [5]:
data

array([[[0.76139955, 0.85126911, 0.41308691, 0.40199999],
        [0.96232628, 0.99582465, 0.36186397, 0.54936689],
        [0.10147976, 0.16372052, 0.51280173, 0.5090997 ]],

       [[0.83486783, 0.24398366, 0.20364594, 0.56315545],
        [0.32603714, 0.4300027 , 0.35309983, 0.32997648],
        [0.26772747, 0.12935133, 0.2057052 , 0.50347333]]])

In [6]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
arr = np.array([[1,2,3,4],[1,2,3,4]]) #This method is used to create a numpy array with our own values

In [9]:
type(arr) #This method returns the type of the array, ndarray is n-dimensional array

numpy.ndarray

# 2. Read

In [11]:
# Attributes
shape = data.shape # (rows, columns)
size = data.size # total number of elements
types = data.dtype # data type of elements

print("Shape: ", shape)
print("Size: ", size)
print("Types: ", types)

Shape:  (2, 3, 4)
Size:  24
Types:  float64


In [26]:
types 

dtype('float64')

In [18]:
# Slicing
arr = data[0] #It will return the first array of the array
slicer = data[0][0:2] #It takes the 2 first rows of the first array
reverse = data[-1]  #It will return the last array of the array
singleval = data[0][0][0] #It will return the first value of the first array of the array

print(data)
print()
print()
print(arr)
print()
print(slicer)
print()
print(reverse)
print()
print(singleval)


[[[0.29754521 0.19088793 0.4933393  0.14605659]
  [0.56719725 0.68573608 0.50375865 0.5280663 ]
  [0.24042    0.35234896 0.0386629  0.24907636]]

 [[0.30395779 0.99609347 0.54032039 0.50594562]
  [0.33790961 0.70410867 0.49256839 0.88714011]
  [0.88099432 0.36290885 0.29607573 0.90728808]]]


[[0.29754521 0.19088793 0.4933393  0.14605659]
 [0.56719725 0.68573608 0.50375865 0.5280663 ]
 [0.24042    0.35234896 0.0386629  0.24907636]]

[[0.29754521 0.19088793 0.4933393  0.14605659]
 [0.56719725 0.68573608 0.50375865 0.5280663 ]]

[[0.30395779 0.99609347 0.54032039 0.50594562]
 [0.33790961 0.70410867 0.49256839 0.88714011]
 [0.88099432 0.36290885 0.29607573 0.90728808]]

0.2975452070062846


In [34]:
singleval

0.480031081005698

In [35]:
data

array([[[0.48003108, 0.44146385, 0.80173342, 0.36955555],
        [0.36791853, 0.96672089, 0.02690897, 0.05000183],
        [0.51120249, 0.09960263, 0.78821282, 0.85545042]],

       [[0.67808393, 0.46217333, 0.80645816, 0.93515466],
        [0.92385328, 0.04500892, 0.83364112, 0.94561375],
        [0.356634  , 0.83439379, 0.82842758, 0.48934849]]])

# 3. Update

In [26]:
list1 = np.random.rand(10) #It creates a array of 10 random numbers between 0 and 1  
list2 = np.random.rand(10) #It creates a array of 10 random numbers between 0 and 1

In [38]:
list2

array([0.38704184, 0.53632305, 0.9944246 , 0.44505152, 0.64292829,
       0.30036371, 0.62623128, 0.98110138, 0.24716036, 0.10309413])

In [39]:
# Basic Math
add = np.add(list1, list2) #It adds the elements of both arrays
sub = np.subtract(list1, list2) #It subtracts the elements of both arrays
div = np.divide(list1, list2) #It divides the elements of both arrays
mult = np.multiply(list1, list2) #It multiplies the elements of both arrays
dot = np.dot(list1, list2) #np.dot() is used to compute the dot product of two arrays which is useful to see if vectors points in the same direction

In [45]:
dot

2.9501773252530117

In [34]:
# Stat Functions SAP - LEMs "Un SAPo comiendo pan de LEMbas"
sqrt = np.sqrt(25) #calculates the square root of 25
ab = np.abs(-2) #calculates the absolute value of -2 
power = np.power(2,7) #calculates 2 to the power of 7 f
log = np.log(25) #calculates the natural log of 25 
exps = np.exp([2,3]) #it calculates the exponential of 2 and 3 for each element in the array
mins = np.min(list1) #it calculates the minimum value among the elements o array
maxs = np.max(list1) #it calculates the maximum value between the elements of array

In [37]:
maxs

0.936255686386591

In [57]:
data

array([[[0.48003108, 0.44146385, 0.80173342, 0.36955555],
        [0.36791853, 0.96672089, 0.02690897, 0.05000183],
        [0.51120249, 0.09960263, 0.78821282, 0.85545042]],

       [[0.67808393, 0.46217333, 0.80645816, 0.93515466],
        [0.92385328, 0.04500892, 0.83364112, 0.94561375],
        [0.356634  , 0.83439379, 0.82842758, 0.48934849]]])

In [59]:
data[0][0][0] = 700

In [60]:
data

array([[[7.00000000e+02, 4.41463849e-01, 8.01733417e-01, 3.69555550e-01],
        [3.67918528e-01, 9.66720888e-01, 2.69089716e-02, 5.00018320e-02],
        [5.11202492e-01, 9.96026268e-02, 7.88212818e-01, 8.55450419e-01]],

       [[6.78083930e-01, 4.62173332e-01, 8.06458161e-01, 9.35154662e-01],
        [9.23853275e-01, 4.50089233e-02, 8.33641123e-01, 9.45613753e-01],
        [3.56634000e-01, 8.34393794e-01, 8.28427576e-01, 4.89348492e-01]]])

In [62]:
data.sort() #sort the data in ascending order
data

array([[[3.69555550e-01, 4.41463849e-01, 8.01733417e-01, 7.00000000e+02],
        [2.69089716e-02, 5.00018320e-02, 3.67918528e-01, 9.66720888e-01],
        [9.96026268e-02, 5.11202492e-01, 7.88212818e-01, 8.55450419e-01]],

       [[4.62173332e-01, 6.78083930e-01, 8.06458161e-01, 9.35154662e-01],
        [4.50089233e-02, 8.33641123e-01, 9.23853275e-01, 9.45613753e-01],
        [3.56634000e-01, 4.89348492e-01, 8.28427576e-01, 8.34393794e-01]]])

In [38]:
print(data.shape) #it will give the shape of the array which is 2D array with 3 rows and 4 columns
print(data)

(2, 3, 4)
[[[0.29754521 0.19088793 0.4933393  0.14605659]
  [0.56719725 0.68573608 0.50375865 0.5280663 ]
  [0.24042    0.35234896 0.0386629  0.24907636]]

 [[0.30395779 0.99609347 0.54032039 0.50594562]
  [0.33790961 0.70410867 0.49256839 0.88714011]
  [0.88099432 0.36290885 0.29607573 0.90728808]]]


In [39]:

data = data.reshape((2,2,-1)) #we are reshaping the array and the -1 means that we don't care about the dimension of the last axis
print(data.shape)
print(data)


(2, 2, 6)
[[[0.29754521 0.19088793 0.4933393  0.14605659 0.56719725 0.68573608]
  [0.50375865 0.5280663  0.24042    0.35234896 0.0386629  0.24907636]]

 [[0.30395779 0.99609347 0.54032039 0.50594562 0.33790961 0.70410867]
  [0.49256839 0.88714011 0.88099432 0.36290885 0.29607573 0.90728808]]]


In [67]:
zeroes = np.zeros((8)) #we create an array of 8 zeroes
print(zeroes) #we print the array
zeroes = np.append(zeroes, [3,4]) #we append 3 and 4 to the array
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [68]:
zeroes = np.insert(zeroes, 2, 1) #Here we are inserting 1 at index 2 on the array named zeroes that was defined in the previous cell
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [40]:
data

array([[[0.29754521, 0.19088793, 0.4933393 , 0.14605659, 0.56719725,
         0.68573608],
        [0.50375865, 0.5280663 , 0.24042   , 0.35234896, 0.0386629 ,
         0.24907636]],

       [[0.30395779, 0.99609347, 0.54032039, 0.50594562, 0.33790961,
         0.70410867],
        [0.49256839, 0.88714011, 0.88099432, 0.36290885, 0.29607573,
         0.90728808]]])

In [41]:
np.delete(data, 0, axis=0) #delete the first array

array([[[0.30395779, 0.99609347, 0.54032039, 0.50594562, 0.33790961,
         0.70410867],
        [0.49256839, 0.88714011, 0.88099432, 0.36290885, 0.29607573,
         0.90728808]]])

In [48]:
print(np.shape(data)) # returns the shape of the array
print(data)
print()
print()
print(np.delete(data, 0, axis=1)) # deletes the the first row across all the layers (sub-arrays)

#Important: When working with 3D arrays in NumPy, the axis parameter becomes crucial in determining which dimension you're operating on:

#axis=0: Operates on the "layers (subarrays)". => print(np.delete(arr_3d, 1, axis=0)) # deletes the second layer (second sub-array - index 1)
#axis=1: Operates on the rows across all layers. => print(np.delete(arr_3d, 2, axis=1)) # deletes the third row across all layers
#axis=2: Operates on the columns across all rows and layers. =>print(np.delete(arr_3d, 0, axis=2)) # deletes the first column across all layers and rows

#Deleting Multiple Layers
#print(np.delete(arr_3d, [0, 2], axis=0)) => deletes the first and third layers (sub-arrays - indices 0 and 2)


(2, 2, 6)
[[[0.29754521 0.19088793 0.4933393  0.14605659 0.56719725 0.68573608]
  [0.50375865 0.5280663  0.24042    0.35234896 0.0386629  0.24907636]]

 [[0.30395779 0.99609347 0.54032039 0.50594562 0.33790961 0.70410867]
  [0.49256839 0.88714011 0.88099432 0.36290885 0.29607573 0.90728808]]]


[[[0.50375865 0.5280663  0.24042    0.35234896 0.0386629  0.24907636]]

 [[0.49256839 0.88714011 0.88099432 0.36290885 0.29607573 0.90728808]]]


In [71]:
np.save("new array", data)

In [72]:
test = np.load("new array.npy")

In [73]:
test

array([[[3.69555550e-01, 4.41463849e-01, 8.01733417e-01, 7.00000000e+02,
         2.69089716e-02, 5.00018320e-02],
        [3.67918528e-01, 9.66720888e-01, 9.96026268e-02, 5.11202492e-01,
         7.88212818e-01, 8.55450419e-01]],

       [[4.62173332e-01, 6.78083930e-01, 8.06458161e-01, 9.35154662e-01,
         4.50089233e-02, 8.33641123e-01],
        [9.23853275e-01, 9.45613753e-01, 3.56634000e-01, 4.89348492e-01,
         8.28427576e-01, 8.34393794e-01]]])

In [ ]:
print('testing')